// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyy0NDmHvBexahRTeU8LtZLl_uAoc4fnY',
    appId: '1:729601043390:web:4c4d11c96047613133a7ef',
    messagingSenderId: '729601043390',
    projectId: 'fluttertest-7d29f',
    authDomain: 'fluttertest-7d29f.firebaseapp.com',
    storageBucket: 'fluttertest-7d29f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFF_qzaItU24HqxmTe5F42vkAY7oe2XbA',
    appId: '1:729601043390:android:94b5fd3883cbd3e533a7ef',
    messagingSenderId: '729601043390',
    projectId: 'fluttertest-7d29f',
    storageBucket: 'fluttertest-7d29f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeZxq4BHYdXEWonx6XiDVKgCmutXwSbAo',
    appId: '1:729601043390:ios:ffd627774f57bc9633a7ef',
    messagingSenderId: '729601043390',
    projectId: 'fluttertest-7d29f',
    storageBucket: 'fluttertest-7d29f.appspot.com',
    iosBundleId: 'com.example.pruebaone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeZxq4BHYdXEWonx6XiDVKgCmutXwSbAo',
    appId: '1:729601043390:ios:5a172950f629b96233a7ef',
    messagingSenderId: '729601043390',
    projectId: 'fluttertest-7d29f',
    storageBucket: 'fluttertest-7d29f.appspot.com',
    iosBundleId: 'com.example.pruebaone.RunnerTests',
  );
}
